### PR TITLE
TKNECO-27: REVISION `main` by Default and Documentation

### PR DESCRIPTION
**Pull request by otaviof**
Project cover and improving parameters description.

### CODE REVIEW

**Comment by otaviof** [comment]
Should we have `REVISION` default to `main`, instead of making the parameter required?

**Comment by vdemeester** [comment]
> Should we have `REVISION` default to `main`, instead of making the parameter required?

Yes 👼🏼

**Comment by otaviof** [comment]
> > Should we have `REVISION` default to `main`, instead of making the parameter required?
> 
> Yes 👼🏼

Cool! Let me change that too 🏃‍♀️

**Comment by otaviof** [comment]
> > > Should we have `REVISION` default to `main`, instead of making the parameter required?
> > 
> > 
> > Yes 👼🏼
> 
> Cool! Let me change that too 🏃‍♀️

@vdemeester please consider the latest changes.

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
