### PR TITLE
Fix the issue of not displaying the result COMMIT for git-clone

### PR DESCRIPTION
**Pull request by savitaashture**
Fixes: https://issues.redhat.com/browse/SRVKP-5572

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by savitaashture** [comment]
@vdemeester i see CI is failure because of infra what to do if it continuous as i am planning this PR for 1.15.1

**Comment by savitaashture** [comment]
@vdemeester @Senjuti256 @Aneesh-M-Bhat 

I see below reason for CI failure for `ci/prow/images` 
```
Writing manifest to image destination
STEP 2/12: ENV "BUILD_LOGLEVEL"="0"
STEP 3/12: ADD ci/kubernetes.repo /etc/yum.repos.d/
STEP 4/12: RUN yum install -y kubectl httpd-tools jq make git which
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```

Its something to do with infra

as the PR change doesn't include much it just the variable correct from `commit` to `COMMIT`

So merging this without CI for 1.15.1 release

**Pull request merged**
