### PR TITLE
[SRVKP-6164] Removed Extra Load-Scripts Step

### PR DESCRIPTION
**Pull request by Aneesh-M-Bhat**
https://issues.redhat.com/browse/SRVKP-6164

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/retest

**Comment by savitaashture** [comment]
@Aneesh-M-Bhat reason for failure for both version
```
Pipeline version: v0.59.2

task.tekton.dev/git-cli created
task.tekton.dev/git-clone created
error: resource mapping not found for name: "git-clone" namespace: "" from "STDIN": no matches for kind "StepAction" in version "tekton.dev/v1beta1"
ensure CRDs are installed first
---
```

```
Pipeline version: v0.56.6

task.tekton.dev/git-cli created
task.tekton.dev/git-clone created
error: resource mapping not found for name: "git-clone" namespace: "" from "STDIN": no matches for kind "StepAction" in version "tekton.dev/v1beta1"
ensure CRDs are installed first
```

**Comment by savitaashture** [comment]
If we put `v1alpha1` then catalog-cd will fail to understand the version because catlog-cd uses latest pipeline version that's where i bumped version to `v1beta1` here https://github.com/openshift-pipelines/task-git/commit/9042ed2c1386fad39d65d9ed6d9caf098cf2c1b9

I think we can merge and we can add 1.16 jobs once we released till that time we can ensure
```
ci/prow/osp-nightly-ocp-415-e2e
```
CI success for task-git

**Pull request merged**
