### PR TITLE
Migrated Task from v1beta1 to v1

### PR DESCRIPTION
**Pull request by Senjuti256**
Signed off :- @Senjuti256 <sde@redhat.com>

### CODE REVIEW

**Comment by Senjuti256** [comment]
@vdemeester

**Comment by vdemeester** [comment]
`apiVersion: tekton.dev/v1beta1` needs to change 👼🏼

**Comment by Senjuti256** [comment]
Done @vdemeester

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
